# Generated by Django 2.0.4 on 2018-04-11 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='spells',
            field=models.ManyToManyField(to='junk.Spell'),
        ),
        migrations.AddField(
            model_name='guild',
            name='wizards',
            field=models.ManyToManyField(to='junk.Wizard'),
        ),
    ]
