# Generated by Django 2.0.4 on 2018-04-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0002_auto_20180411_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='wizard',
            field=models.ForeignKey(blank=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='junk.Wizard'),
        ),
    ]
