# Generated by Django 2.0.4 on 2018-04-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0003_auto_20180412_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='wizard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='junk.Wizard'),
        ),
    ]
