# Generated by Django 2.0.7 on 2018-07-17 17:39

from django.db import migrations, models
import django.db.models.deletion
import tree.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0006_auto_20180514_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('path', tree.fields.PathField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='junk.Space')),
            ],
            options={
                'ordering': ('path',),
            },
        ),
    ]
