# Generated by Django 2.0.7 on 2018-07-17 17:40

from django.db import migrations
from tree.operations import CreateTreeTrigger

class Migration(migrations.Migration):
    dependencies = [
        ('tree', '0001_initial'),
        ('junk', '0007_space'),
    ]

    operations = [
        CreateTreeTrigger('junk.Space'),
    ]
